name: Deploy subgraph to Nova

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Source Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install

      - name: Add execute permission to scripts
        run: |
          chmod +x ./scripts/*.sh

      - name: Deploy arbitrum-amm subgraph to hosted service
        env:
          GRAPH_DEPLOY_URL: https://api.thegraph.com/deploy/
          GRAPH_IPFS_URL: https://api.thegraph.com/ipfs/
          GRAPH_SUBGRAPH_NAME: tech-arbswap-nova/arbswap
          GRAPH_ACCESS_TOKEN: ${{ secrets.MAINNET_SUBGRAPH_ACCESS_TOKEN }}
          GRAPH_NETWORK: arbitrum-nova
        run: |
          yarn envsub ./.env.arbitrum.template.nova ./.env.arbitrum.nova
          yarn deploy:arbitrum:nova
          rm ./.env.arbitrum.nova
